version: '3.1'
services:

    postgres:
        image: postgres:9.6
        expose:
            - "5432"
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        networks:
          - airflow

    webserver:
        image: puckel/docker-airflow:1.10.4
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            #- FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            #- EXECUTOR=Celery            
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
            # - AIRFLOW__CORE__REMOTE_LOGGING=True
            # - AIRFLOW__CORE__LOG_FILENAME_TEMPLATE={{ ti.dag_id }}.log
            # - POSTGRES_USER=airflow
            # - POSTGRES_PASSWORD=airflow
            # - POSTGRES_DB=airflow
            # - REDIS_PASSWORD=redispass
        volumes:

            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
            # - "8793:8793" # log files? static content?
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        networks:
          - airflow

    # redis:
    #     image: 'redis:3.2.7'
    #     # command: redis-server --requirepass redispass

    # flower:
    #     image: puckel/docker-airflow:1.10.2
    #     restart: always
    #     depends_on:
    #         - redis
    #     environment:
    #         - EXECUTOR=Celery
    #         # - REDIS_PASSWORD=redispass
    #     ports:
    #         - "5555:5555"
    #     command: flower

    # scheduler:
    #     image: puckel/docker-airflow:1.10.2
    #     restart: always
    #     depends_on:
    #         - webserver
    #     volumes:
    #         - ./dags:/usr/local/airflow/dags
    #         # Uncomment to include custom plugins
    #         # - ./plugins:/usr/local/airflow/plugins
    #     environment:
    #         - LOAD_EX=n
    #         - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    #         - EXECUTOR=Celery
    #         # - POSTGRES_USER=airflow
    #         # - POSTGRES_PASSWORD=airflow
    #         # - POSTGRES_DB=airflow
    #         # - REDIS_PASSWORD=redispass
    #     command: scheduler

    # worker:
    #     image: puckel/docker-airflow:1.10.2
    #     restart: always
    #     depends_on:
    #         - scheduler
    #     volumes:
    #         - ./dags:/usr/local/airflow/dags
    #         # Uncomment to include custom plugins
    #         # - ./plugins:/usr/local/airflow/plugins
    #     environment:
    #         - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    #         - EXECUTOR=Celery
    #         # - POSTGRES_USER=airflow
    #         # - POSTGRES_PASSWORD=airflow
    #         # - POSTGRES_DB=airflow
    #         # - REDIS_PASSWORD=redispass
    #     command: worker



networks:
  airflow:
    driver: bridge